---

port: 4000
host: 0.0.0.0
safe: false
url: "https://applications_cognitive_science.github.io"


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title: Applications Cognitive Science
keywords: Cognitive Science, IA, Public Policy, Data Science,
description: How does the human brain acquire or reacquire knowledge? How does it interact with technological objects or with other brains? The cognitive engineering track introduces some of the major concepts and findings of the study of the brain and its functions (perception, action, decision-making, consciousness, memory, language, social cognition, etc.) and illustrates how this fundamental knowledge can help to resolve complex engineering problems involving human operators.
#source_link:
favicon: img/ens.png
#touch_icon:
#google_analytics_key:


### template colors, used site-wide via css ###
colors:
  black:
    light: '#303030'
    dark: '#111111'
  white:
    light: '#f5f5f5'
    dark: '#f8f8f8'
  blue:
    light: '#3c9eec'
    dark: '#49a7e9'
  green:
    light: '#a3d832'
    dark: '#9bcf2f'
  purple:
    light: '#c869bf'
    dark: '#c869bf'
  orange:
    light: '#faaf22'
    dark: '#fab125'
  turquoise:
    light: '#0fbfcf'
    dark: '#0fbfcf'
  color1:
    light: '#E3E1D3'
    dark: '#DCBB7D'
  color2:
    light: '#B65558'
    dark: '#8F4244'
  color3:
    light: '#828BA1'
    dark: '#595F6D'
  color4:
    light: '#C8BFCA'
    dark: '#9A8A98'
  color5:
    light: '#A1A1A1'
    dark: '#757575'
